{
 "title": "Bee",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "number of handled connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bee_libp2p_handled_connection_count{}"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - bee_process_start_time_seconds{}"
    }
   ]
  },
  {
   "title": "bee version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "bee_info{}", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "go version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "go_info{}", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "swap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_swap_total_received{}[1m])",
     "legendFormat": "received"
    },
    {
     "expr": "increase(bee_swap_total_sent{}[1m])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "bee_swap_total_received{}" }
   ]
  },
  {
   "title": "received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "bee_swap_total_received{}" }
   ]
  },
  {
   "title": "events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_accounting_credit_events_count{}[1m])",
     "legendFormat": "credit"
    },
    {
     "expr": "increase(bee_accounting_debit_events_count{}[1m])",
     "legendFormat": "debit"
    }
   ]
  },
  {
   "title": "credit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " bee_accounting_credit_events_count"
    }
   ]
  },
  {
   "title": "debit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " bee_accounting_debit_events_count"
    }
   ]
  },
  {
   "title": "totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bee_accounting_total_credited_amount{}",
     "legendFormat": "credited"
    },
    {
     "expr": "bee_accounting_total_debited_amount{}",
     "legendFormat": "debited"
    }
   ]
  },
  {
   "title": "credited",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bee_accounting_total_credited_amount"
    }
   ]
  },
  {
   "title": "debited",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bee_accounting_total_debited_amount"
    }
   ]
  }
 ]
}