name: "Main"
on:
  pull_request:
  push:
    branches:
      - "master"
      - "main"
    paths-ignore:
      - "README.md"
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: 'Type of version increment: patch, minor, or major'
        required: true
        default: patch
        options:
        - patch
        - minor
        - major

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build test
    if: github.event_name != 'push'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npx @dappnode/dappnodesdk build --skip_save

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Publish
        env:
          VERSION_TYPE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version_type || 'patch' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
          DEVELOPER_ADDRESS: "0xdAD64d07A318476dc48257a0bB53a8e9a26C6B33"
        run: npx @dappnode/dappnodesdk publish $VERSION_TYPE --github-release --eth_provider=${{ secrets.ETH_PROVIDER }} --content_provider=pinata
